# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da058a75d535ca5247ab8d94ff3ffed103b89524593a9ed4753f56c8b0e4d852482c0703a015a5bf990d512a19a23c55cc0e4742ff4c715ca0b5c54f0e0ba2eb

test:
  secret_key_base: a529cbafd4932f27e47f56e76ab1d8538618bef084096f925e76e6e6439fcc06cb713b4f0e2df41fef46eced9063ef84d5edd30d8912df05cc3c9c45ba956302

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
